# Generated by Django 3.1.3 on 2023-02-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego', models.TextField(default='Apex legends')),
                ('fecha_de_lanzamiento', models.TextField(default='')),
                ('descripcion', models.TextField(default='una batalla por trios o duos')),
                ('tipo', models.TextField(default='de disparos')),
                ('creador', models.TextField(default='chino')),
                ('personajes', models.TextField(default='lifeline, octane, wraith, ect')),
                ('enemigos', models.TextField(default='equipo contrario')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('musica', models.TextField(default='12')),
                ('version', models.TextField(default='12')),
            ],
        ),
    ]
