# Generated by Django 3.1.3 on 2023-02-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20230224_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creador',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='enemigos',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='juego',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='musica',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='personajes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='tipo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='version',
            field=models.TextField(default=''),
        ),
    ]
