# Generated by Django 3.1.3 on 2023-04-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20230228_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
